name: complex

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              run: echo $(date '+%Y-%m-%d')
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              run: Get-Date
    job3:
        name: Third Job
        runs-on: macos-latest
        steps:
            - name: Step one
              run: echo $(date '+%Y-%m-%d')
    job4:
        name: Fourth Job
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: Step one
              run: echo $(date '+%Y-%m-%d')
